const PLANTAS_INICIALES = [
  {
    id: 'tomate',
    nombre: 'Tomate',
    categoria: 'verdura',
    emoji: '🍅',
    siembra: { norte: { inicio: 3, fin: 5 }, sur: { inicio: 9, fin: 11 } },
    cosecha: { norte: { inicio: 7, fin: 9 }, sur: { inicio: 1, fin: 3 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, rico en materia orgánica',
    profundidad: '0.5 cm',
    espaciado: '50 cm entre plantas',
    companieras: ['albahaca', 'cebolla', 'zanahoria', 'perejil'],
    notas: 'Necesita tutores. Evitar encharcamiento. Asociar con albahaca mejora el sabor.'
  },
  {
    id: 'lechuga',
    nombre: 'Lechuga',
    categoria: 'verdura',
    emoji: '🥬',
    siembra: { norte: { inicio: 2, fin: 10 }, sur: { inicio: 8, fin: 4 } },
    cosecha: { norte: { inicio: 4, fin: 12 }, sur: { inicio: 10, fin: 6 } },
    sol: 'sombra parcial',
    riego: 'moderado',
    suelo: 'franco, rico en nitrógeno',
    profundidad: '0.3 cm',
    espaciado: '25 cm entre plantas',
    companieras: ['zanahoria', 'rábano', 'fresa', 'cebolla'],
    notas: 'Se puede cosechar hoja por hoja. Sembrar escalonadamente para tener lechuga todo el año.'
  },
  {
    id: 'zanahoria',
    nombre: 'Zanahoria',
    categoria: 'verdura',
    emoji: '🥕',
    siembra: { norte: { inicio: 2, fin: 7 }, sur: { inicio: 8, fin: 1 } },
    cosecha: { norte: { inicio: 5, fin: 10 }, sur: { inicio: 11, fin: 4 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'arenoso, profundo y suelto',
    profundidad: '0.5 cm',
    espaciado: '5 cm entre plantas',
    companieras: ['cebolla', 'puerro', 'romero', 'salvia'],
    notas: 'No trasplantar, sembrar directo. Evitar suelos pedregosos o se deforman.'
  },
  {
    id: 'cebolla',
    nombre: 'Cebolla',
    categoria: 'verdura',
    emoji: '🧅',
    siembra: { norte: { inicio: 2, fin: 4 }, sur: { inicio: 8, fin: 10 } },
    cosecha: { norte: { inicio: 6, fin: 9 }, sur: { inicio: 12, fin: 3 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, bien drenado',
    profundidad: '1 cm',
    espaciado: '10 cm entre plantas',
    companieras: ['zanahoria', 'remolacha', 'lechuga', 'fresa'],
    notas: 'Dejar de regar 2 semanas antes de cosechar. Curar al sol después de cosechar.'
  },
  {
    id: 'ajo',
    nombre: 'Ajo',
    categoria: 'verdura',
    emoji: '🧄',
    siembra: { norte: { inicio: 10, fin: 11 }, sur: { inicio: 4, fin: 5 } },
    cosecha: { norte: { inicio: 6, fin: 7 }, sur: { inicio: 12, fin: 1 } },
    sol: 'pleno sol',
    riego: 'bajo',
    suelo: 'franco, bien drenado',
    profundidad: '3 cm',
    espaciado: '10 cm entre plantas',
    companieras: ['fresa', 'tomate', 'remolacha', 'manzanilla'],
    notas: 'Plantar dientes individuales con la punta hacia arriba. Excelente repelente natural.'
  },
  {
    id: 'pimiento',
    nombre: 'Pimiento',
    categoria: 'verdura',
    emoji: '🫑',
    siembra: { norte: { inicio: 2, fin: 4 }, sur: { inicio: 8, fin: 10 } },
    cosecha: { norte: { inicio: 7, fin: 10 }, sur: { inicio: 1, fin: 4 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, profundo y fresco',
    profundidad: '0.5 cm',
    espaciado: '40 cm entre plantas',
    companieras: ['albahaca', 'cebolla', 'zanahoria', 'perejil'],
    notas: 'Proteger del viento. Necesita calor. Evitar plantar cerca de hinojo.'
  },
  {
    id: 'pepino',
    nombre: 'Pepino',
    categoria: 'verdura',
    emoji: '🥒',
    siembra: { norte: { inicio: 3, fin: 5 }, sur: { inicio: 9, fin: 11 } },
    cosecha: { norte: { inicio: 6, fin: 9 }, sur: { inicio: 12, fin: 3 } },
    sol: 'pleno sol',
    riego: 'alto',
    suelo: 'franco, rico en compost',
    profundidad: '1 cm',
    espaciado: '30 cm entre plantas',
    companieras: ['maíz', 'frijol', 'girasol', 'eneldo'],
    notas: 'Necesita riego constante para evitar amargor. Trepador, usar tutores.'
  },
  {
    id: 'calabacin',
    nombre: 'Calabacín',
    categoria: 'verdura',
    emoji: '🥒',
    siembra: { norte: { inicio: 3, fin: 6 }, sur: { inicio: 9, fin: 12 } },
    cosecha: { norte: { inicio: 6, fin: 10 }, sur: { inicio: 12, fin: 4 } },
    sol: 'pleno sol',
    riego: 'alto',
    suelo: 'franco, rico en materia orgánica',
    profundidad: '2 cm',
    espaciado: '80 cm entre plantas',
    companieras: ['maíz', 'frijol', 'albahaca', 'capuchina'],
    notas: 'Cosechar cuando aún están tiernos. Revisar bajo las hojas para plagas.'
  },
  {
    id: 'berenjena',
    nombre: 'Berenjena',
    categoria: 'verdura',
    emoji: '🍆',
    siembra: { norte: { inicio: 2, fin: 4 }, sur: { inicio: 8, fin: 10 } },
    cosecha: { norte: { inicio: 7, fin: 10 }, sur: { inicio: 1, fin: 4 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, profundo y fértil',
    profundidad: '0.5 cm',
    espaciado: '50 cm entre plantas',
    companieras: ['albahaca', 'pimiento', 'frijol', 'tomillo'],
    notas: 'Necesita calor y protección del viento. Cosechar antes que la piel pierda brillo.'
  },
  {
    id: 'brocoli',
    nombre: 'Brócoli',
    categoria: 'verdura',
    emoji: '🥦',
    siembra: { norte: { inicio: 6, fin: 8 }, sur: { inicio: 12, fin: 2 } },
    cosecha: { norte: { inicio: 9, fin: 11 }, sur: { inicio: 3, fin: 5 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, compacto y fértil',
    profundidad: '0.5 cm',
    espaciado: '45 cm entre plantas',
    companieras: ['remolacha', 'cebolla', 'manzanilla', 'romero'],
    notas: 'Cortar la cabeza principal para estimular brotes laterales. No plantar cerca de fresas.'
  },
  {
    id: 'coliflor',
    nombre: 'Coliflor',
    categoria: 'verdura',
    emoji: '🥦',
    siembra: { norte: { inicio: 6, fin: 8 }, sur: { inicio: 12, fin: 2 } },
    cosecha: { norte: { inicio: 9, fin: 11 }, sur: { inicio: 3, fin: 5 } },
    sol: 'pleno sol',
    riego: 'alto',
    suelo: 'franco, rico en boro',
    profundidad: '0.5 cm',
    espaciado: '50 cm entre plantas',
    companieras: ['apio', 'cebolla', 'romero', 'salvia'],
    notas: 'Atar las hojas sobre la cabeza para mantenerla blanca. Exigente en nutrientes.'
  },
  {
    id: 'espinaca',
    nombre: 'Espinaca',
    categoria: 'verdura',
    emoji: '🥬',
    siembra: { norte: { inicio: 2, fin: 4 }, sur: { inicio: 8, fin: 10 } },
    cosecha: { norte: { inicio: 4, fin: 6 }, sur: { inicio: 10, fin: 12 } },
    sol: 'sombra parcial',
    riego: 'moderado',
    suelo: 'franco, rico en nitrógeno',
    profundidad: '1 cm',
    espaciado: '15 cm entre plantas',
    companieras: ['fresa', 'cebolla', 'ajo', 'rábano'],
    notas: 'Sembrar escalonadamente. Florece con días largos, cosechar antes.'
  },
  {
    id: 'acelga',
    nombre: 'Acelga',
    categoria: 'verdura',
    emoji: '🥬',
    siembra: { norte: { inicio: 2, fin: 9 }, sur: { inicio: 8, fin: 3 } },
    cosecha: { norte: { inicio: 4, fin: 11 }, sur: { inicio: 10, fin: 5 } },
    sol: 'pleno sol a sombra parcial',
    riego: 'moderado',
    suelo: 'franco, profundo',
    profundidad: '1 cm',
    espaciado: '25 cm entre plantas',
    companieras: ['zanahoria', 'repollo', 'cebolla', 'frijol'],
    notas: 'Cosechar hojas exteriores primero. Muy resistente y productiva.'
  },
  {
    id: 'remolacha',
    nombre: 'Remolacha',
    categoria: 'verdura',
    emoji: '🫘',
    siembra: { norte: { inicio: 3, fin: 7 }, sur: { inicio: 9, fin: 1 } },
    cosecha: { norte: { inicio: 6, fin: 10 }, sur: { inicio: 12, fin: 4 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, suelto y profundo',
    profundidad: '1 cm',
    espaciado: '10 cm entre plantas',
    companieras: ['cebolla', 'ajo', 'lechuga', 'repollo'],
    notas: 'No trasplantar. El tamaño óptimo de cosecha es como una pelota de golf.'
  },
  {
    id: 'papa',
    nombre: 'Papa',
    categoria: 'verdura',
    emoji: '🥔',
    siembra: { norte: { inicio: 3, fin: 5 }, sur: { inicio: 9, fin: 11 } },
    cosecha: { norte: { inicio: 7, fin: 9 }, sur: { inicio: 1, fin: 3 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, suelto y ácido',
    profundidad: '10 cm',
    espaciado: '30 cm entre plantas',
    companieras: ['frijol', 'maíz', 'repollo', 'caléndula'],
    notas: 'Aporcar cuando las plantas tengan 20 cm. No plantar cerca de tomate o pepino.'
  },
  {
    id: 'rabanito',
    nombre: 'Rabanito',
    categoria: 'verdura',
    emoji: '🫘',
    siembra: { norte: { inicio: 2, fin: 5 }, sur: { inicio: 8, fin: 11 } },
    cosecha: { norte: { inicio: 3, fin: 6 }, sur: { inicio: 9, fin: 12 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, suelto',
    profundidad: '0.5 cm',
    espaciado: '5 cm entre plantas',
    companieras: ['lechuga', 'zanahoria', 'espinaca', 'frijol'],
    notas: 'Crece muy rápido (3-4 semanas). Sembrar escalonadamente cada 15 días.'
  },
  {
    id: 'arveja',
    nombre: 'Arveja',
    categoria: 'verdura',
    emoji: '🫛',
    siembra: { norte: { inicio: 2, fin: 4 }, sur: { inicio: 8, fin: 10 } },
    cosecha: { norte: { inicio: 5, fin: 7 }, sur: { inicio: 11, fin: 1 } },
    sol: 'pleno sol a sombra parcial',
    riego: 'moderado',
    suelo: 'franco, bien drenado',
    profundidad: '2 cm',
    espaciado: '5 cm entre plantas',
    companieras: ['zanahoria', 'maíz', 'rábano', 'menta'],
    notas: 'Necesita soportes para trepar. Fija nitrógeno en el suelo.'
  },
  {
    id: 'haba',
    nombre: 'Haba',
    categoria: 'verdura',
    emoji: '🫛',
    siembra: { norte: { inicio: 10, fin: 11 }, sur: { inicio: 4, fin: 5 } },
    cosecha: { norte: { inicio: 4, fin: 6 }, sur: { inicio: 10, fin: 12 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, arcilloso',
    profundidad: '5 cm',
    espaciado: '20 cm entre plantas',
    companieras: ['maíz', 'calabaza', 'papa', 'menta'],
    notas: 'Resiste heladas. Excelente abono verde por su fijación de nitrógeno.'
  },
  {
    id: 'frijol',
    nombre: 'Frijol',
    categoria: 'verdura',
    emoji: '🫘',
    siembra: { norte: { inicio: 4, fin: 7 }, sur: { inicio: 10, fin: 1 } },
    cosecha: { norte: { inicio: 6, fin: 9 }, sur: { inicio: 12, fin: 3 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, bien drenado',
    profundidad: '3 cm',
    espaciado: '10 cm entre plantas',
    companieras: ['maíz', 'calabaza', 'pepino', 'fresa'],
    notas: 'No plantar cerca de cebolla o ajo. Fija nitrógeno en el suelo.'
  },
  {
    id: 'maiz',
    nombre: 'Maíz',
    categoria: 'verdura',
    emoji: '🌽',
    siembra: { norte: { inicio: 4, fin: 6 }, sur: { inicio: 10, fin: 12 } },
    cosecha: { norte: { inicio: 8, fin: 10 }, sur: { inicio: 2, fin: 4 } },
    sol: 'pleno sol',
    riego: 'alto',
    suelo: 'franco, profundo y fértil',
    profundidad: '3 cm',
    espaciado: '25 cm entre plantas',
    companieras: ['frijol', 'calabaza', 'pepino', 'girasol'],
    notas: 'Plantar en bloques para mejor polinización. Viento ayuda a la polinización.'
  },
  {
    id: 'zapallo',
    nombre: 'Zapallo',
    categoria: 'verdura',
    emoji: '🎃',
    siembra: { norte: { inicio: 4, fin: 6 }, sur: { inicio: 10, fin: 12 } },
    cosecha: { norte: { inicio: 9, fin: 11 }, sur: { inicio: 3, fin: 5 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, rico en compost',
    profundidad: '2 cm',
    espaciado: '100 cm entre plantas',
    companieras: ['maíz', 'frijol', 'girasol', 'albahaca'],
    notas: 'Ocupa mucho espacio. Se almacena muy bien por meses en lugar fresco.'
  },
  {
    id: 'apio',
    nombre: 'Apio',
    categoria: 'verdura',
    emoji: '🥬',
    siembra: { norte: { inicio: 2, fin: 4 }, sur: { inicio: 8, fin: 10 } },
    cosecha: { norte: { inicio: 6, fin: 9 }, sur: { inicio: 12, fin: 3 } },
    sol: 'pleno sol a sombra parcial',
    riego: 'alto',
    suelo: 'franco, muy húmedo y rico',
    profundidad: '0.3 cm',
    espaciado: '25 cm entre plantas',
    companieras: ['puerro', 'coliflor', 'tomate', 'cebolla'],
    notas: 'Necesita mucha agua. Acolchar para mantener humedad.'
  },
  {
    id: 'puerro',
    nombre: 'Puerro',
    categoria: 'verdura',
    emoji: '🥬',
    siembra: { norte: { inicio: 3, fin: 5 }, sur: { inicio: 9, fin: 11 } },
    cosecha: { norte: { inicio: 9, fin: 11 }, sur: { inicio: 3, fin: 5 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, profundo y fértil',
    profundidad: '1 cm',
    espaciado: '15 cm entre plantas',
    companieras: ['zanahoria', 'fresa', 'apio', 'cebolla'],
    notas: 'Aporcar para blanquear el tallo. Soporta heladas ligeras.'
  },
  {
    id: 'rucula',
    nombre: 'Rúcula',
    categoria: 'verdura',
    emoji: '🥬',
    siembra: { norte: { inicio: 2, fin: 10 }, sur: { inicio: 8, fin: 4 } },
    cosecha: { norte: { inicio: 3, fin: 11 }, sur: { inicio: 9, fin: 5 } },
    sol: 'pleno sol a sombra parcial',
    riego: 'moderado',
    suelo: 'franco, fértil',
    profundidad: '0.3 cm',
    espaciado: '10 cm entre plantas',
    companieras: ['lechuga', 'escarola', 'remolacha', 'frijol'],
    notas: 'Cosechar hojas jóvenes para mejor sabor. Crece muy rápido.'
  },
  {
    id: 'escarola',
    nombre: 'Escarola',
    categoria: 'verdura',
    emoji: '🥬',
    siembra: { norte: { inicio: 6, fin: 8 }, sur: { inicio: 12, fin: 2 } },
    cosecha: { norte: { inicio: 9, fin: 11 }, sur: { inicio: 3, fin: 5 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, ligero',
    profundidad: '0.5 cm',
    espaciado: '25 cm entre plantas',
    companieras: ['lechuga', 'cebolla', 'remolacha', 'frijol'],
    notas: 'Blanquear atando las hojas exteriores 2 semanas antes de cosechar.'
  },
  {
    id: 'batata',
    nombre: 'Batata',
    categoria: 'verdura',
    emoji: '🍠',
    siembra: { norte: { inicio: 4, fin: 6 }, sur: { inicio: 10, fin: 12 } },
    cosecha: { norte: { inicio: 9, fin: 11 }, sur: { inicio: 3, fin: 5 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'arenoso, suelto',
    profundidad: '10 cm',
    espaciado: '30 cm entre plantas',
    companieras: ['frijol', 'caléndula', 'tomillo', 'orégano'],
    notas: 'Necesita clima cálido. Cosechar antes de las primeras heladas.'
  },
  {
    id: 'jengibre',
    nombre: 'Jengibre',
    categoria: 'verdura',
    emoji: '🫚',
    siembra: { norte: { inicio: 3, fin: 5 }, sur: { inicio: 9, fin: 11 } },
    cosecha: { norte: { inicio: 10, fin: 12 }, sur: { inicio: 4, fin: 6 } },
    sol: 'sombra parcial',
    riego: 'moderado',
    suelo: 'franco, rico en humus',
    profundidad: '5 cm',
    espaciado: '20 cm entre plantas',
    companieras: ['cúrcuma', 'pimiento', 'menta', 'cilantro'],
    notas: 'Plantar rizomas con brotes. Necesita alta humedad ambiente.'
  },
  {
    id: 'curcuma',
    nombre: 'Cúrcuma',
    categoria: 'verdura',
    emoji: '🫚',
    siembra: { norte: { inicio: 3, fin: 5 }, sur: { inicio: 9, fin: 11 } },
    cosecha: { norte: { inicio: 10, fin: 12 }, sur: { inicio: 4, fin: 6 } },
    sol: 'sombra parcial',
    riego: 'moderado',
    suelo: 'franco, rico en materia orgánica',
    profundidad: '5 cm',
    espaciado: '25 cm entre plantas',
    companieras: ['jengibre', 'albahaca', 'menta', 'cúrcuma'],
    notas: 'Las hojas se ponen amarillas cuando está lista para cosechar.'
  },
  {
    id: 'hinojo',
    nombre: 'Hinojo',
    categoria: 'verdura',
    emoji: '🥬',
    siembra: { norte: { inicio: 6, fin: 8 }, sur: { inicio: 12, fin: 2 } },
    cosecha: { norte: { inicio: 9, fin: 11 }, sur: { inicio: 3, fin: 5 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, profundo',
    profundidad: '0.5 cm',
    espaciado: '30 cm entre plantas',
    companieras: ['salvia', 'cebolla', 'remolacha', 'pepino'],
    notas: 'No plantar cerca de hinojo. Atrae insectos benéficos. No asociar con tomate.'
  },
  {
    id: 'mandioca',
    nombre: 'Mandioca',
    categoria: 'verdura',
    emoji: '🪴',
    siembra: { norte: { inicio: 3, fin: 5 }, sur: { inicio: 9, fin: 11 } },
    cosecha: { norte: { inicio: 10, fin: 12 }, sur: { inicio: 4, fin: 6 } },
    sol: 'pleno sol',
    riego: 'bajo',
    suelo: 'arenoso, suelto',
    profundidad: '10 cm',
    espaciado: '80 cm entre plantas',
    companieras: ['frijol', 'maíz', 'calabaza', 'maní'],
    notas: 'Resistente a sequía. Cosechar entre 8-12 meses. Tóxica si se consume cruda.'
  },
  {
    id: 'quinua',
    nombre: 'Quinua',
    categoria: 'verdura',
    emoji: '🌾',
    siembra: { norte: { inicio: 4, fin: 6 }, sur: { inicio: 10, fin: 12 } },
    cosecha: { norte: { inicio: 9, fin: 11 }, sur: { inicio: 3, fin: 5 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, bien drenado',
    profundidad: '1 cm',
    espaciado: '20 cm entre plantas',
    companieras: ['frijol', 'maíz', 'papa', 'caléndula'],
    notas: 'Lavar bien las semillas para quitar saponinas. Resistente a condiciones adversas.'
  },
  {
    id: 'fresa',
    nombre: 'Fresa',
    categoria: 'fruta',
    emoji: '🍓',
    siembra: { norte: { inicio: 8, fin: 10 }, sur: { inicio: 2, fin: 4 } },
    cosecha: { norte: { inicio: 4, fin: 6 }, sur: { inicio: 10, fin: 12 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, ácido y bien drenado',
    profundidad: 'superficial',
    espaciado: '30 cm entre plantas',
    companieras: ['lechuga', 'espinaca', 'cebolla', 'ajo'],
    notas: 'Acolchar con paja para mantener frutos limpios. Renovar plantas cada 3 años.'
  },
  {
    id: 'sandia',
    nombre: 'Sandía',
    categoria: 'fruta',
    emoji: '🍉',
    siembra: { norte: { inicio: 4, fin: 6 }, sur: { inicio: 10, fin: 12 } },
    cosecha: { norte: { inicio: 7, fin: 9 }, sur: { inicio: 1, fin: 3 } },
    sol: 'pleno sol',
    riego: 'alto',
    suelo: 'arenoso, bien drenado',
    profundidad: '2 cm',
    espaciado: '100 cm entre plantas',
    companieras: ['maíz', 'girasol', 'albahaca', 'orégano'],
    notas: 'Necesita mucho espacio y calor. Golpear el fruto para ver si está maduro.'
  },
  {
    id: 'melon',
    nombre: 'Melón',
    categoria: 'fruta',
    emoji: '🍈',
    siembra: { norte: { inicio: 4, fin: 6 }, sur: { inicio: 10, fin: 12 } },
    cosecha: { norte: { inicio: 7, fin: 9 }, sur: { inicio: 1, fin: 3 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'arenoso, bien drenado',
    profundidad: '2 cm',
    espaciado: '80 cm entre plantas',
    companieras: ['maíz', 'girasol', 'caléndula', 'capuchina'],
    notas: 'Reducir riego en maduración para mejorar dulzor. Cosechar cuando se desprenda fácil.'
  },
  {
    id: 'perejil',
    nombre: 'Perejil',
    categoria: 'hierba',
    emoji: '🌿',
    siembra: { norte: { inicio: 2, fin: 9 }, sur: { inicio: 8, fin: 3 } },
    cosecha: { norte: { inicio: 4, fin: 11 }, sur: { inicio: 10, fin: 5 } },
    sol: 'sombra parcial',
    riego: 'moderado',
    suelo: 'franco, rico en nitrógeno',
    profundidad: '0.3 cm',
    espaciado: '15 cm entre plantas',
    companieras: ['tomate', 'espárrago', 'cebolla', 'fresa'],
    notas: 'Tarda en germinar (3-4 semanas). Remojar semillas 24h antes para acelerar.'
  },
  {
    id: 'albahaca',
    nombre: 'Albahaca',
    categoria: 'hierba',
    emoji: '🌿',
    siembra: { norte: { inicio: 3, fin: 6 }, sur: { inicio: 9, fin: 12 } },
    cosecha: { norte: { inicio: 5, fin: 9 }, sur: { inicio: 11, fin: 3 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, fértil y húmedo',
    profundidad: '0.3 cm',
    espaciado: '25 cm entre plantas',
    companieras: ['tomate', 'pimiento', 'berenjena', 'orégano'],
    notas: 'Pinchar la flor para que crezca frondosa. No soporta heladas.'
  },
  {
    id: 'cilantro',
    nombre: 'Cilantro',
    categoria: 'hierba',
    emoji: '🌿',
    siembra: { norte: { inicio: 2, fin: 9 }, sur: { inicio: 8, fin: 3 } },
    cosecha: { norte: { inicio: 4, fin: 11 }, sur: { inicio: 10, fin: 5 } },
    sol: 'sombra parcial',
    riego: 'moderado',
    suelo: 'franco, bien drenado',
    profundidad: '0.5 cm',
    espaciado: '10 cm entre plantas',
    companieras: ['tomate', 'espinaca', 'pimiento', 'cebolla'],
    notas: 'Crece rápido y florece fácil. Sembrar cada 3 semanas para tener siempre.'
  },
  {
    id: 'menta',
    nombre: 'Menta',
    categoria: 'hierba',
    emoji: '🌿',
    siembra: { norte: { inicio: 3, fin: 6 }, sur: { inicio: 9, fin: 12 } },
    cosecha: { norte: { inicio: 5, fin: 10 }, sur: { inicio: 11, fin: 4 } },
    sol: 'sombra parcial',
    riego: 'alto',
    suelo: 'franco, húmedo',
    profundidad: 'superficial',
    espaciado: '30 cm entre plantas',
    companieras: ['repollo', 'tomate', 'zanahoria', 'caléndula'],
    notas: 'Invasiva, plantar en maceta o con barrera. Se propaga por rizomas.'
  },
  {
    id: 'romero',
    nombre: 'Romero',
    categoria: 'hierba',
    emoji: '🌿',
    siembra: { norte: { inicio: 3, fin: 6 }, sur: { inicio: 9, fin: 12 } },
    cosecha: { norte: { inicio: 4, fin: 12 }, sur: { inicio: 10, fin: 6 } },
    sol: 'pleno sol',
    riego: 'bajo',
    suelo: 'franco, bien drenado, alcalino',
    profundidad: '0.3 cm',
    espaciado: '50 cm entre plantas',
    companieras: ['salvia', 'tomillo', 'orégano', 'lavanda'],
    notas: 'No tolera encharcamiento. Pode regularmente para mantener forma.'
  },
  {
    id: 'tomillo',
    nombre: 'Tomillo',
    categoria: 'hierba',
    emoji: '🌿',
    siembra: { norte: { inicio: 4, fin: 6 }, sur: { inicio: 10, fin: 12 } },
    cosecha: { norte: { inicio: 6, fin: 10 }, sur: { inicio: 12, fin: 4 } },
    sol: 'pleno sol',
    riego: 'bajo',
    suelo: 'franco, muy bien drenado',
    profundidad: '0.3 cm',
    espaciado: '30 cm entre plantas',
    companieras: ['berenjena', 'papa', 'fresa', 'repollo'],
    notas: 'Resistente a sequía. Atrae abejas. Podar después de floración.'
  },
  {
    id: 'oregano',
    nombre: 'Orégano',
    categoria: 'hierba',
    emoji: '🌿',
    siembra: { norte: { inicio: 3, fin: 6 }, sur: { inicio: 9, fin: 12 } },
    cosecha: { norte: { inicio: 6, fin: 10 }, sur: { inicio: 12, fin: 4 } },
    sol: 'pleno sol',
    riego: 'bajo',
    suelo: 'franco, seco y bien drenado',
    profundidad: '0.3 cm',
    espaciado: '25 cm entre plantas',
    companieras: ['tomate', 'pimiento', 'calabacín', 'albahaca'],
    notas: 'Cosechar antes de floración para mejor sabor. Se seca muy bien.'
  },
  {
    id: 'laurel',
    nombre: 'Laurel',
    categoria: 'hierba',
    emoji: '🌿',
    siembra: { norte: { inicio: 2, fin: 4 }, sur: { inicio: 8, fin: 10 } },
    cosecha: { norte: { inicio: 6, fin: 12 }, sur: { inicio: 12, fin: 6 } },
    sol: 'pleno sol a sombra parcial',
    riego: 'moderado',
    suelo: 'franco, bien drenado',
    profundidad: 'superficial',
    espaciado: '200 cm entre plantas',
    companieras: ['romero', 'tomillo', 'salvia', 'orégano'],
    notas: 'Crece como arbusto o árbol pequeño. Hojas aromáticas para cocina.'
  },
  {
    id: 'eneldo',
    nombre: 'Eneldo',
    categoria: 'hierba',
    emoji: '🌿',
    siembra: { norte: { inicio: 3, fin: 6 }, sur: { inicio: 9, fin: 12 } },
    cosecha: { norte: { inicio: 5, fin: 8 }, sur: { inicio: 11, fin: 2 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, bien drenado',
    profundidad: '0.5 cm',
    espaciado: '20 cm entre plantas',
    companieras: ['repollo', 'cebolla', 'pepino', 'lechuga'],
    notas: 'Atrae insectos benéficos. No plantar cerca de hinojo o se cruzan.'
  },
  {
    id: 'salvia',
    nombre: 'Salvia',
    categoria: 'hierba',
    emoji: '🌿',
    siembra: { norte: { inicio: 3, fin: 6 }, sur: { inicio: 9, fin: 12 } },
    cosecha: { norte: { inicio: 5, fin: 10 }, sur: { inicio: 11, fin: 4 } },
    sol: 'pleno sol',
    riego: 'bajo',
    suelo: 'franco, bien drenado',
    profundidad: '0.3 cm',
    espaciado: '40 cm entre plantas',
    companieras: ['romero', 'tomillo', 'repollo', 'zanahoria'],
    notas: 'Repelente natural de plagas. No plantar cerca de pepino.'
  },
  {
    id: 'estragon',
    nombre: 'Estragón',
    categoria: 'hierba',
    emoji: '🌿',
    siembra: { norte: { inicio: 3, fin: 5 }, sur: { inicio: 9, fin: 11 } },
    cosecha: { norte: { inicio: 5, fin: 10 }, sur: { inicio: 11, fin: 4 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, seco y bien drenado',
    profundidad: '0.3 cm',
    espaciado: '30 cm entre plantas',
    companieras: ['berenjena', 'pimiento', 'tomate', 'calabaza'],
    notas: 'Multiplicar por esquejes o división de mata. Semillas raramente viables.'
  },
  {
    id: 'cebollin',
    nombre: 'Cebollín',
    categoria: 'hierba',
    emoji: '🌿',
    siembra: { norte: { inicio: 2, fin: 6 }, sur: { inicio: 8, fin: 12 } },
    cosecha: { norte: { inicio: 4, fin: 10 }, sur: { inicio: 10, fin: 4 } },
    sol: 'pleno sol a sombra parcial',
    riego: 'moderado',
    suelo: 'franco, fértil',
    profundidad: '0.5 cm',
    espaciado: '15 cm entre plantas',
    companieras: ['zanahoria', 'tomate', 'fresa', 'manzanilla'],
    notas: 'Cortar con tijera a 3 cm del suelo. Florece con vistosas flores comestibles.'
  },
  {
    id: 'calendula',
    nombre: 'Caléndula',
    categoria: 'flor',
    emoji: '🌼',
    siembra: { norte: { inicio: 3, fin: 6 }, sur: { inicio: 9, fin: 12 } },
    cosecha: { norte: { inicio: 5, fin: 10 }, sur: { inicio: 11, fin: 4 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, bien drenado',
    profundidad: '1 cm',
    espaciado: '25 cm entre plantas',
    companieras: ['tomate', 'frijol', 'pimiento', 'brócoli'],
    notas: 'Atrae polinizadores. Pétalos comestibles. Repelente natural de nematodos.'
  },
  {
    id: 'capuchina',
    nombre: 'Capuchina',
    categoria: 'flor',
    emoji: '🌸',
    siembra: { norte: { inicio: 3, fin: 6 }, sur: { inicio: 9, fin: 12 } },
    cosecha: { norte: { inicio: 5, fin: 10 }, sur: { inicio: 11, fin: 4 } },
    sol: 'pleno sol',
    riego: 'bajo',
    suelo: 'franco, pobre',
    profundidad: '1 cm',
    espaciado: '25 cm entre plantas',
    companieras: ['tomate', 'rábano', 'pepino', 'calabacín'],
    notas: 'Flores y hojas comestibles (sabor picante). Atrae pulgones (planta trampa).'
  },
  {
    id: 'borraja',
    nombre: 'Borraja',
    categoria: 'flor',
    emoji: '🌼',
    siembra: { norte: { inicio: 3, fin: 6 }, sur: { inicio: 9, fin: 12 } },
    cosecha: { norte: { inicio: 5, fin: 9 }, sur: { inicio: 11, fin: 3 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, bien drenado',
    profundidad: '1 cm',
    espaciado: '40 cm entre plantas',
    companieras: ['tomate', 'fresa', 'calabaza', 'repollo'],
    notas: 'Atrae abejas. Flores comestibles con sabor a pepino. Se resiembra sola.'
  },
  {
    id: 'lavanda',
    nombre: 'Lavanda',
    categoria: 'flor',
    emoji: '💜',
    siembra: { norte: { inicio: 4, fin: 6 }, sur: { inicio: 10, fin: 12 } },
    cosecha: { norte: { inicio: 6, fin: 8 }, sur: { inicio: 12, fin: 2 } },
    sol: 'pleno sol',
    riego: 'bajo',
    suelo: 'franco, alcalino y muy bien drenado',
    profundidad: '0.3 cm',
    espaciado: '40 cm entre plantas',
    companieras: ['romero', 'tomillo', 'orégano', 'salvia'],
    notas: 'Pode después de floración. Atrae polinizadores. Repelente de polillas.'
  },
  {
    id: 'girasol',
    nombre: 'Girasol',
    categoria: 'flor',
    emoji: '🌻',
    siembra: { norte: { inicio: 4, fin: 6 }, sur: { inicio: 10, fin: 12 } },
    cosecha: { norte: { inicio: 8, fin: 10 }, sur: { inicio: 2, fin: 4 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, bien drenado',
    profundidad: '3 cm',
    espaciado: '40 cm entre plantas',
    companieras: ['pepino', 'calabaza', 'maíz', 'frijol'],
    notas: 'Semillas comestibles. Atrae polinizadores y pájaros. Sigue al sol.'
  },
  {
    id: 'manzanilla',
    nombre: 'Manzanilla',
    categoria: 'flor',
    emoji: '🌼',
    siembra: { norte: { inicio: 2, fin: 6 }, sur: { inicio: 8, fin: 12 } },
    cosecha: { norte: { inicio: 4, fin: 8 }, sur: { inicio: 10, fin: 2 } },
    sol: 'pleno sol a sombra parcial',
    riego: 'moderado',
    suelo: 'franco, seco',
    profundidad: 'superficial',
    espaciado: '15 cm entre plantas',
    companieras: ['repollo', 'cebolla', 'pepino', 'brócoli'],
    notas: 'Mejora el sabor de las plantas cercanas. Atrae polinizadores.'
  },
  {
    id: 'dienteleon',
    nombre: 'Diente de León',
    categoria: 'flor',
    emoji: '🌼',
    siembra: { norte: { inicio: 2, fin: 9 }, sur: { inicio: 8, fin: 3 } },
    cosecha: { norte: { inicio: 3, fin: 11 }, sur: { inicio: 9, fin: 5 } },
    sol: 'pleno sol a sombra parcial',
    riego: 'bajo',
    suelo: 'franco, cualquier tipo',
    profundidad: 'superficial',
    espaciado: '15 cm entre plantas',
    companieras: ['lechuga', 'cebolla', 'ajo', 'perejil'],
    notas: 'Todas las partes son comestibles y medicinales. Raíz, hojas y flores.'
  },
  {
    id: 'amaranto',
    nombre: 'Amaranto',
    categoria: 'verdura',
    emoji: '🌾',
    siembra: { norte: { inicio: 4, fin: 6 }, sur: { inicio: 10, fin: 12 } },
    cosecha: { norte: { inicio: 8, fin: 10 }, sur: { inicio: 2, fin: 4 } },
    sol: 'pleno sol',
    riego: 'moderado',
    suelo: 'franco, bien drenado',
    profundidad: '0.5 cm',
    espaciado: '30 cm entre plantas',
    companieras: ['maíz', 'frijol', 'calabaza', 'girasol'],
    notas: 'Hojas comestibles como verdura. Semillas ricas en proteínas. Resistente a sequía.'
  }
];
